### ISSUE TITLE
Enable K2 Compiler

### ISSUE THREAD

**Issue by matejsemancik** [futuredapp/kmp-futured-template#24]
Things which need to be resolved before
- https://github.com/icerockdev/moko-resources/issues/564
- https://github.com/arkivanov/Decompose/issues/470

**Comment by RudolfHladik** [comment]
- [ ] Skie support for Kotlin 2.0 https://github.com/touchlab/SKIE/releases
- [ ] Koin + Annotations support for Kotlin 2.0 https://github.com/InsertKoinIO/koin/releases
